### PR TITLE
Display all Api clients

### PR DESCRIPTION
**Pull request by hassanad94**

### CODE REVIEW

**Comment by hassanad94** [comment]
I dont know why, but it doesn't want to refresh the deploy...

**Comment by tusmester** [comment]
> I dont know why, but it doesn't want to refresh the deploy...

In case of deployment issues you can review the actions section for deploy logs.
https://github.com/SenseNet/sn-client/actions

**Comment by tusmester** [comment]
It seems the new deploy succeeded. The new url is:
https://641cb08d81c55d0784b212f1--sn-app-dev.netlify.app

**Comment by hassanad94** [comment]
I have changed clients and spa tabs. Here is the new deployment url: 
https://641da11a3e4bec23ff5da884--sn-app-dev.netlify.app

**Review by tusmester — APPROVED** [review]

**Review by VargaJoe — APPROVED** [review]

**Review by kavics — APPROVED** [review]

**Pull request merged**
