### PR TITLE
Correct Date Time Format

### PR DESCRIPTION
**Pull request by hassanad94**
Thats the first part of the issue.

- ( Bug fix )
- I fixed the format of the control. Format: "yyyy MMMM dd"

### CODE REVIEW

**Comment by hassanad94** [comment]
I have more things to do, but i pushed-ed it so that i can see if any error occur.

**Comment by hassanad94** [comment]
Currently im ready with:
- Bug Fix
- Format display
- Min Date

**Comment by hassanad94** [comment]
- If BirthDate is the minimum value than its treated like null

Notes to discuss: 
- Currently there is not way you can set datepickers to null after you set a value.
- There is a part of the code which will never execute in the current system.

**Comment by hassanad94** [comment]
### Summary for this Issue
## changes
- Date display format
- Min Date Error Fixed
- null value handle

## discuss 
- changeTemplatedValue and its usecase.

**Review by kavics — APPROVED** [review]

**Review by tusmester — APPROVED** [review]

**Pull request merged**
