### PR TITLE
E2E localization tests

### PR DESCRIPTION
**Pull request by dlemstra**
This PR adds the E2E tests for #795. I was not able to properly test the `cy.get` with `data-test="editor-title"` because this is not yet available in the test environment. And the right click menu only contains `Download` and `Browse` instead of all the items listed in the issue. Is this a bug or is that the expected result?

### CODE REVIEW

**Comment by herflis** [comment]
Hi @dlemstra thanks for your awesome pull request, it is under review and I'm sure we can approve it in no time. In the meantime can you please add a comment to the related issue ([#795](https://github.com/sensenet/sn-client/issues/795)), this way I will be able to assign it to you. It would make later administration easier for us :) Thanks! 💙

**Comment by herflis** [comment]
@dlemstra Thank you for taking the time to help us! We greatly appreciate your contribution and the extra cases you've added to the tests 💙 You will get the extra sensenet-Hacktoberfest swag 🧦. We will contact you via email after the Hacktoberfest event. Hope you are having a great Hacktoberfest! 🎉 🙂

**Comment by NileshPatel17** [comment]
@dlemstra curious to know why `data-test="Localization"` was not added? Was it assumed that data-test already exists?

**Comment by dlemstra** [comment]
@NileshPatel17 I don't understand what you are asking.

**Pull request merged**
