### PR TITLE
Field controls rework

### PR DESCRIPTION
**Pull request by taki9**

### CODE REVIEW

**Comment by pusztaienike** [comment]
1. It seems that if a quill is empty there is no message appears like "No value set". Is it possible to add this?

image
image

2. The checkbox has the default primary color. Could it be #26a69a?
image

**Review by pusztaienike — APPROVED** [review]
Can we add padding here to the left-side?

2020-11-10_10h31_05

2020-11-10_10h32_04

**Comment by herflis** [comment]
Checkboxes cannot be unchecked
checkbox

**Review by pusztaienike — APPROVED** [review]

**Comment by taki9** [comment]
> Checkboxes cannot be unchecked
> checkbox

fixed

**Comment by herflis** [comment]
something is not okay with the field control docs on the storybook page

image

**Pull request merged**
